name: Deploy via SFTP

on:
  push:
    branches:
      - main
    paths:
      - 'Website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: sftp://${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local-dir: Website/
          server-dir: ${{ secrets.SFTP_TARGET_DIR }}
          protocol: sftp
